WIP : Add Change Request and Update Log
uclibs/application_portfolio pull request #301
Opened 2023-05-16 14:39 UTC by scherztc

2023-08-11 16:54 UTC, crowesn requested changes
This is for UI issues found while testing the feature manually. Code review pending.
 
1. ChangeRequest#edit broken locale?
<img width="393" alt="Screen Shot 2023-08-11 at 12 36 16 PM" src="https://github.com/uclibs/application_portfolio/assets/1069588/1418c0d9-3cc5-4821-b0a7-7453119b177a">

2. Change request new/edit form extends above top nav hiding fields. Layout seems to be for mobile but it's not responsive/doesn't change with viewport resizing
<img width="1341" alt="Screen Shot 2023-08-11 at 12 38 04 PM" src="https://github.com/uclibs/application_portfolio/assets/1069588/4afd41a0-c1d1-4b5f-b191-589b63cc68b7">

3. Seems like all the Change Request views have this mobile static sizing
<img width="1307" alt="Screen Shot 2023-08-11 at 12 40 09 PM" src="https://github.com/uclibs/application_portfolio/assets/1069588/3ee1c604-d930-4a24-9358-a81e46c1f1d4">

4. On the Software Record show view, consider grouping the change request table and new change request buttons.
<img width="980" alt="Screen Shot 2023-08-11 at 12 42 28 PM" src="https://github.com/uclibs/application_portfolio/assets/1069588/e06487a7-a0e3-49e4-9d22-cf913e9198cc">

5. The select for change request software record id is missing a label.
<img width="313" alt="Screen Shot 2023-08-11 at 12 52 11 PM" src="https://github.com/uclibs/application_portfolio/assets/1069588/66d6481e-963b-440b-a274-e7b5dd09024c">

2023-08-14 14:21 UTC, crowesn requested changes
Change_request access/auth by user role needs to be expanded and refined using patterns outlined in petergate [documentation](https://github.com/elorest/petergate). There are some conditionals in one of the views that hint at what levels of access each role should have. Add role contexts/shared examples to specs to further document access/auth for each role.

2023-08-15 15:01 UTC, scherztc commented
https://github.com/uclibs/application_portfolio/wiki/Roles-in-Application-Portfolio

2023-08-18 14:53 UTC, crowesn requested changes
This is ready to go aside from one small runtime error bug.

2023-08-18 14:53 UTC, crowesn commented on app/views/software_records/_upgrade_history.html.erb
> +                <td><%= link_to 'Edit', edit_change_request_path(change_requests), { :class => "btn btn-primary" } %></td>
```
ActionView::Template::Error (undefined local variable or method `change_requests' for #<ActionView::Base:0x0000000000e9e8>
Did you mean?  change_request
               change_requests_url
               change_request_url):
    32:                 <td><%= link_to 'View', change_request , { :class => "btn btn-success" }%></td>
    33:               <% elsif current_user.role.to_s == "owner" %>
    34:                 <td><%= link_to 'View', change_request , { :class => "btn btn-success" }%></td>
    35:                 <td><%= link_to 'Edit', edit_change_request_path(change_requests), { :class => "btn btn-primary" } %></td>
    36:               <% else %>
    37:                 <td><%= link_to 'View', change_request , { :class => "btn btn-success" }%></td>
    38:                 <td><%= link_to 'Edit', edit_change_request_path(change_request), { :class => "btn btn-primary" } %></td>
  
app/views/software_records/_upgrade_history.html.erb:35
app/views/software_records/_upgrade_history.html.erb:25
app/views/software_records/show.html.erb:59
```

2023-08-18 14:53 UTC, crowesn commented on app/views/software_records/_upgrade_history.html.erb
> +                <td><%= link_to 'Edit', edit_change_request_path(change_requests), { :class => "btn btn-primary" } %></td>
little typo: argument "change_requests" in `edit_change_request_path` helper should be singular "change_request"

2023-08-18 18:03 UTC, crowesn approved these changes

2023-08-18 18:03 UTC, merged