Adds server and certificate fields to SoftwareRecords.
uclibs/application_portfolio pull request #311
Opened 2023-06-06 21:14 UTC by scherztc

Fixes #270 
Fixes #247

2023-07-17 19:07 UTC, crowesn commented on app/views/software_records/_server_environment.html.erb
> +            <dt class="inline-block">Tracks uptime wiht Monastic:<span style="color: white; font-weight: normal"><%= @software_record.track_uptime %></span></dt>
Typo 'wiht'

2023-07-17 19:13 UTC, crowesn commented on app/views/software_records/_form_server_environment.html.erb
> +                <%= form.label :monitor_certificates, 'Track uptime?' %><br/>
Form label text here should be "Track Certificates". I think this came over from copy/paste?
"Track Uptime" label is duplicated. 

![Screen Shot 2023-07-17 at 3 12 35 PM](https://github.com/uclibs/application_portfolio/assets/1069588/228b8836-fcbf-424e-a680-6d4c2ae1866c)

2023-07-17 19:16 UTC, crowesn requested changes
See inline comments with some issues on incorrect label text and a typo. Consider covering these in the specs.

2023-07-18 17:38 UTC, scherztc reviewed
@crowesn : The typos and test have been updated and ready for merging.

2023-07-18 18:36 UTC, crowesn approved these changes

2023-07-18 18:36 UTC, merged