Bug/multi value
uclibs/application_portfolio pull request #375
Opened 2024-07-15 18:09 UTC by scherztc

Pulled Javascript out of views and into asset pipeline.
Adjusted HTML to get the count and ID right to properly delete 
Product_Owners
Tech_Leads
Departments
Admin_users

2024-07-17 13:40 UTC, Janell-Huyck requested changes

2024-07-17 13:40 UTC, Janell-Huyck commented on app/assets/javascripts/custom.js
Nice choice, moving this code out of app/views/layouts/application.html.erb and app/views/layouts/software_records.html.erb.  I would want to see this broken down into multiple files just to make it more readable and modular.  One possible way to break it down:

- Navigation Control: navigation.js
- Dynamic Input Management: dynamicInputs.js
- Input Sanitization: inputSanitization.js
- Filter Management: filterManagement.js
- Global Initialization: globalInitialization.js

You've also got a console.log in there, around line 68 that could probably be removed.

2024-07-17 13:40 UTC, Janell-Huyck commented on app/views/layouts/application.html.erb
Thanks for fixing the alignments here.  Makes it much easier to read.

2024-07-17 13:40 UTC, Janell-Huyck commented on app/views/layouts/software_records.html.erb
Thanks for fixing the alignments here. Makes it much easier to read.

2024-07-17 13:40 UTC, Janell-Huyck commented on app/views/software_records/_form_general.html.erb
This file is very difficult to read and maintain simply because of its size.  I think the easiest way to handle it would be to break this down into partials.  Each of your sections that you're denoting with a comment like ` <!-- Multiple Departments -->` could easily be a partial in itself that you then include in the view.

2024-07-17 13:40 UTC, Janell-Huyck commented on config/initializers/assets.rb
This change is actually redundant and has a small chance of causing issues in browsers in the future.  While it is important to precompile `custom.js`, your placement of the file `custom.js` means that it's already included in app/assets/javascripts/application.js.  Here's how:

In `application.js` we have the final line: `//= require_tree .`.  That line pulls in to application.js every file within the directory `app/assets/javascripts`.  Since application.js gets precompiled, the code in custom.js is already precompiled.

2024-07-17 13:40 UTC, Janell-Huyck commented on spec/features/software_records/multi_value_spec.rb
These tests are a good start but don't actually test the problem that we're trying to fix.  We had the problem where the wrong item was being deleted.  In addition to checking the number of items after deleting an item, I would want to see these tests checking that the correct one has been deleted.  You can do this by checking that a specific item is not there as well as the correct count.  Something like `expect(page).not_to have_field(with: 'Product Owner 2')` would work.

2024-07-17 13:46 UTC, Janell-Huyck commented
The changed code works appropriately when run locally.  I'm able to correctly add and remove members, and the item I click to delete is the one that's actually removed.

2024-07-23 17:23 UTC, scherztc commented on app/assets/javascripts/custom.js
I broke the javascript into these files :

-rw-r--r--   1 scherztc  staff   724 Jul 17 14:08 filtermanagement.js
-rw-r--r--   1 scherztc  staff   194 Jul 17 14:03 inputsanitization.js
-rw-r--r--   1 scherztc  staff  2418 Jul 17 14:01 multivalueinputs.js
-rw-r--r--   1 scherztc  staff   437 Jul 17 14:08 navigation.js

2024-07-23 17:24 UTC, scherztc commented on app/views/software_records/_form_general.html.erb
I pulled out the view code into the following partials :

-rw-r--r--   1 scherztc  staff  1222 Jul 23 11:54 _form_multi_admin_users.html.erb
-rw-r--r--   1 scherztc  staff  2011 Jul 23 11:55 _form_multi_departments.html.erb
-rw-r--r--   1 scherztc  staff  1981 Jul 23 11:57 _form_multi_developers.html.erb
-rw-r--r--   1 scherztc  staff  1270 Jul 23 12:02 _form_multi_product_owners.html.erb
-rw-r--r--   1 scherztc  staff  1978 Jul 23 12:02 _form_multi_tech_leads.html.erb

2024-07-23 17:26 UTC, scherztc commented on config/initializers/assets.rb
I needed to set the initializer like this to get it working.  I think that in this case, working code wins.   We can make in issue for the initializer refactor if we think it is still important.

2024-07-25 16:44 UTC, Janell-Huyck approved these changes
Thanks for breaking up the giant files.  Let's get this rolling!

2024-07-25 17:41 UTC, merged